dist: trusty
sudo: required
language: scala
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
jdk: oraclejdk8

env:
  matrix:
    - TRAVIS_SBT_VERSION=0.13.16
    - TRAVIS_SBT_VERSION=1.0.1

script:
  - ^^$TRAVIS_SBT_VERSION "scripted sbt-typescript/ignoreCanNotFindModule"
  - ^^$TRAVIS_SBT_VERSION "scripted sbt-typescript/inlinesourcemap"
  - ^^$TRAVIS_SBT_VERSION "scripted sbt-typescript/sourcemap"

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm